# Generated by Django 2.1.7 on 2019-03-09 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='attribute',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
