# Generated by Django 2.1.7 on 2019-10-15 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_attributedescriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributedescriptor',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='attributes.Attribute'),
        ),
    ]
