# Generated by Django 2.1.7 on 2019-03-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
        ('books', '0002_auto_20190301_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Attribute')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='attributes',
            field=models.ManyToManyField(through='books.BookAttributes', to='attributes.Attribute'),
        ),
    ]
