# Generated by Django 2.1.7 on 2019-03-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190306_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='open_library_cover_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='open_library_url',
            field=models.CharField(max_length=255),
        ),
    ]
