# Generated by Django 2.1.7 on 2019-03-09 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190308_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifier',
            name='book',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='identifier_type',
        ),
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='open_library_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='book',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bookattribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookattribute',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='author',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='author',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='book',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='bookattribute',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='bookattribute',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.DeleteModel(
            name='Identifier',
        ),
        migrations.DeleteModel(
            name='IdentifierType',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
