# Generated by Django 2.1.7 on 2019-03-22 21:59
from django.db import migrations


class Migration(migrations.Migration):

    def populateBookStatuses(apps, schema_editor):
        BookListStatus = apps.get_model('user_profiles', 'UserBookStatus')
        db_alias = schema_editor.connection.alias
        BookListStatus.objects.using(db_alias).bulk_create([
            BookListStatus(name='To Read'),
            BookListStatus(name='Reading'),
            BookListStatus(name='Finished'),
        ])

    def reverseBookStatusPopulate(apps, schema_editor):
        BookListStatus = apps.get_model('user_profiles', 'UserBookStatus')
        db_alias = schema_editor.connection.alias
        BookListStatus.objects.using(db_alias).filter(name="To Read").delete()
        BookListStatus.objects.using(db_alias).filter(name="Reading").delete()
        BookListStatus.objects.using(db_alias).filter(name="Finished").delete()

    dependencies = [
        ('user_profiles', '0002_auto_20190322_2138'),
    ]

    operations = [
        migrations.RunPython(populateBookStatuses, reverseBookStatusPopulate)
    ]
