# Generated by Django 2.1.7 on 2019-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_auto_20190330_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='date_finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
