# Generated by Django 2.1.7 on 2019-04-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_auto_20190410_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='user',
            new_name='profile',
        ),
    ]
